---
- name: Apply Deployment manifests
  template:
    src: deployment.yml.j2
    dest: /tmp/{{ item.name }}-deployment.yml
  loop: "{{ deployments }}"
  register: deployment_files

- name: Apply each deployment
  command: kubectl apply -f {{ item.dest }}
  loop: "{{ deployment_files.results }}"

- name: Apply Service manifests
  template:
    src: service.yml.j2
    dest: /tmp/{{ item.name }}-service.yml
  loop: "{{ deployments }}"
  register: service_files

- name: Apply each service
  command: kubectl apply -f {{ item.dest }}
  loop: "{{ service_files.results }}"

- name: Apply Ingress
  template:
    src: ingress.yml.j2
    dest: /tmp/ingress.yml

- name: Deploy ingress
  command: kubectl apply -f /tmp/ingress.yml
