Description: An empty VPC (10.0.0.0/16) with one (public) subnet (/24) with internet gateway and routing table that allows full interaction between subnet and outside world.
Parameters:
  VPCCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC.
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for public subnet 1
    Type: String
    Default: 10.0.1.0/24

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for public subnet 2
    Type: String
    Default: 10.0.2.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for private subnet 1
    Type: String
    Default: 10.0.51.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for private subnet 2
    Type: String
    Default: 10.0.52.0/24

  AvailabilityZone1:
    Description: Please enter the name of the first Availability Zone.
    Type: String
    Default: us-east-1a

  AvailabilityZone2:
    Description: Please enter the name of the first Availability Zone.
    Type: String
    Default: us-east-1b

Resources:
  # We need a VPC.
  CloudShirtVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: true
      Tags: # Good practice is to add tags!
        - Key: Name
          Value: CloudShirtVpc

  # Define internet gateway to allow access to the "outside world"
  CloudShirtInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CloudShirtInternetGateway

  # Connect internet gateway to VPC
  CloudShirtVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref CloudShirtInternetGateway
      VpcId: !Ref CloudShirtVpc

  # Define two (public) subnets on the /24 domain that automatically
  # assigns all instances a public ip on launch
  CloudShirtFirstSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PublicSubnet1CIDR
      AvailabilityZone: !Ref AvailabilityZone1
      MapPublicIpOnLaunch: true
      VpcId: !Ref CloudShirtVpc
      Tags:
        - Key: Name
          Value: CloudShirtFirstSubnet

  CloudShirtSecondSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PublicSubnet2CIDR
      AvailabilityZone: !Ref AvailabilityZone2
      MapPublicIpOnLaunch: true
      VpcId: !Ref CloudShirtVpc
      Tags:
        - Key: Name
          Value: CloudShirtSecondSubnet

  # Add a routing table (and route) to the VPC to route all traffic
  # via the internet gateway
  CloudShirtRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CloudShirtVpc
      Tags:
        - Key: Name
          Value: CloudShirtRouteTable

  # Default route to the internet gateway
  CloudShirtDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref CloudShirtInternetGateway
      RouteTableId: !Ref CloudShirtRouteTable

  # Associate routing table to subnets
  CloudShirtFirstSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref CloudShirtRouteTable
      SubnetId: !Ref CloudShirtFirstSubnet

  CloudShirtSecondSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref CloudShirtRouteTable
      SubnetId: !Ref CloudShirtSecondSubnet

  # Define two (private) subnets on the /24 domain
  CloudShirtFirstPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PrivateSubnet1CIDR
      AvailabilityZone: !Ref AvailabilityZone1
      VpcId: !Ref CloudShirtVpc
      Tags:
        - Key: Name
          Value: CloudShirtFirstPrivateSubnet

  CloudShirtSecondPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PrivateSubnet2CIDR
      AvailabilityZone: !Ref AvailabilityZone2
      VpcId: !Ref CloudShirtVpc
      Tags:
        - Key: Name
          Value: CloudShirtSecondPrivateSubnet

# Define outputs so values can be imported in another template
Outputs:
  VPCRef:
    Description: Reference to the VPC
    Value: !Ref CloudShirtVpc
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", VPC ] ] # Fancy way of making the exported variable called "MyBase:VPC"
  VPCGatewayAttachmentRef:
    Description: Reference to the VPC gateway attachment
    Value: !Ref CloudShirtVPCGatewayAttachment
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", CloudShirtVPCGatewayAttachment ] ]
  CloudShirtRouteTableRef:
    Description: Reference to the VPC route table
    Value: !Ref CloudShirtRouteTable
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", CloudShirtRouteTable ] ]
  CloudShirtFirstSubnetRef:
    Description: Reference to my first (public) subnet
    Value: !Ref CloudShirtFirstSubnet
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", CloudShirtFirstSubnet ] ]
  CloudShirtSecondSubnetRef:
    Description: Reference to my second (public) subnet
    Value: !Ref CloudShirtSecondSubnet
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", CloudShirtSecondSubnet ] ]
  CloudShirtFirstPrivateSubnetRef:
    Description: Reference to my first (private) subnet
    Value: !Ref CloudShirtFirstPrivateSubnet
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", CloudShirtFirstPrivateSubnet ] ]
  CloudShirtSecondPrivateSubnetRef:
    Description: Reference to my second (private) subnet
    Value: !Ref CloudShirtSecondPrivateSubnet
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", CloudShirtSecondPrivateSubnet ] ]
  AvailabilityZone1Ref:
    Description: Reference to Availability Zone 1
    Value: !Ref AvailabilityZone1
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", AvailabilityZone1 ] ]
  AvailabilityZone2Ref:
    Description: Reference to Availability Zone 2
    Value: !Ref AvailabilityZone2
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", AvailabilityZone2 ] ]
