---
- name: Get list of CloudShirt pods
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: cloudshirt
    kind: Pod
    label_selectors:
      - "app=cloudshirt"
  register: cloudshirt_pods

- name: Create local logs directory
  ansible.builtin.file:
    path: "./collected_logs"
    state: directory

- name: Collect logs from each CloudShirt pod
  kubernetes.core.k8s_log:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: cloudshirt
    name: "{{ item.metadata.name }}"
  loop: "{{ cloudshirt_pods.resources }}"
  register: pod_logs

- name: Write logs to local files
  ansible.builtin.copy:
    content: "{{ item.log }}"
    dest: "./collected_logs/{{ item.item.metadata.name }}.log"
  loop: "{{ pod_logs.results }}"

# Optional: AWS logs (if you still run EC2 services)
- name: Collect logs from AWS EC2 instances (if any)
  ansible.builtin.shell: |
    aws logs describe-log-groups --query "logGroups[*].logGroupName" --output text > aws_loggroups.txt
    aws logs filter-log-events --log-group-name /aws/cloudshirt/app --output text > collected_logs/aws_cloudshirt.log
  register: aws_logs
  ignore_errors: yes

# Upload logs to centralized storage
- name: Upload logs to GCS bucket
  ansible.builtin.shell: |
    gsutil cp ./collected_logs/*.log gs://cloudshirt-central-logs/
  ignore_errors: yes
