---
- name: Configure GKE cluster and deploy CloudShirt app
  hosts: local
  vars:
    gcp_project: "k8-cluster-470912"
    gcp_region: "europe-west4"
    cluster_name: "cloudshirt-gke"
    namespace: "cloudshirt"
    image_repo: "europe-west4-docker.pkg.dev/k8-cluster-470912/cloudshirt-docker"
    deployments:
      - name: eshopwebmvc
        image: "{{ image_repo }}/eshopwebmvc:latest"
        port: 80
      - name: eshoppublicapi
        image: "{{ image_repo }}/eshoppublicapi:latest"
        port: 8080
  tasks:
    - name: Authenticate with GCP
      command: gcloud auth activate-service-account --key-file=/root/gcp-key.json

    - name: Get GKE credentials
      command: gcloud container clusters get-credentials {{ cluster_name }} --region {{ gcp_region }} --project {{ gcp_project }}

    - name: Create namespace
      command: kubectl create namespace {{ namespace }}
      ignore_errors: yes

    - name: Deploy CloudShirt applications
      include_role:
        name: gke_deploy
