---
- name: Collect logs from GKE and upload to GCS
  hosts: local
  vars:
    gcp_project: "k8-cluster-470912"
    gcp_region: "europe-west4"
    cluster_name: "cloudshirt-gke"
    log_bucket: "cloudshirt-logs"
    namespace: "cloudshirt"
  tasks:
    - name: Authenticate with GCP
      command: gcloud auth activate-service-account --key-file=/root/gcp-key.json

    - name: Get GKE credentials
      command: gcloud container clusters get-credentials {{ cluster_name }} --region {{ gcp_region }} --project {{ gcp_project }}

    - name: Collect pod logs
      shell: |
        mkdir -p /tmp/gke-logs
        for pod in $(kubectl get pods -n {{ namespace }} -o name); do
          kubectl logs -n {{ namespace }} $pod > /tmp/gke-logs/$(basename $pod).log
        done

    - name: Upload logs to GCS
      command: gcloud storage cp /tmp/gke-logs gs://{{ log_bucket }}/ --recursive
